/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Lembrete
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-09-29T00:57:32.159Z")
public class Lembrete {
  @SerializedName("arquivado")
  private Boolean arquivado = null;

  @SerializedName("conteudo")
  private String conteudo = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("modificado")
  private Long modificado = null;

  /**
   * Gets or Sets prioridade
   */
  @JsonAdapter(PrioridadeEnum.Adapter.class)
  public enum PrioridadeEnum {
    BAIXA("BAIXA"),
    
    MEDIA("MEDIA"),
    
    ALTA("ALTA");

    private String value;

    PrioridadeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PrioridadeEnum fromValue(String text) {
      for (PrioridadeEnum b : PrioridadeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PrioridadeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PrioridadeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PrioridadeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PrioridadeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("prioridade")
  private PrioridadeEnum prioridade = null;

  public Lembrete arquivado(Boolean arquivado) {
    this.arquivado = arquivado;
    return this;
  }

   /**
   * Get arquivado
   * @return arquivado
  **/
  @ApiModelProperty(value = "")
  public Boolean isArquivado() {
    return arquivado;
  }

  public void setArquivado(Boolean arquivado) {
    this.arquivado = arquivado;
  }

  public Lembrete conteudo(String conteudo) {
    this.conteudo = conteudo;
    return this;
  }

   /**
   * Get conteudo
   * @return conteudo
  **/
  @ApiModelProperty(value = "")
  public String getConteudo() {
    return conteudo;
  }

  public void setConteudo(String conteudo) {
    this.conteudo = conteudo;
  }

  public Lembrete id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Lembrete modificado(Long modificado) {
    this.modificado = modificado;
    return this;
  }

   /**
   * Get modificado
   * @return modificado
  **/
  @ApiModelProperty(value = "")
  public Long getModificado() {
    return modificado;
  }

  public void setModificado(Long modificado) {
    this.modificado = modificado;
  }

  public Lembrete prioridade(PrioridadeEnum prioridade) {
    this.prioridade = prioridade;
    return this;
  }

   /**
   * Get prioridade
   * @return prioridade
  **/
  @ApiModelProperty(value = "")
  public PrioridadeEnum getPrioridade() {
    return prioridade;
  }

  public void setPrioridade(PrioridadeEnum prioridade) {
    this.prioridade = prioridade;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Lembrete lembrete = (Lembrete) o;
    return Objects.equals(this.arquivado, lembrete.arquivado) &&
        Objects.equals(this.conteudo, lembrete.conteudo) &&
        Objects.equals(this.id, lembrete.id) &&
        Objects.equals(this.modificado, lembrete.modificado) &&
        Objects.equals(this.prioridade, lembrete.prioridade);
  }

  @Override
  public int hashCode() {
    return Objects.hash(arquivado, conteudo, id, modificado, prioridade);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Lembrete {\n");
    
    sb.append("    arquivado: ").append(toIndentedString(arquivado)).append("\n");
    sb.append("    conteudo: ").append(toIndentedString(conteudo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    modificado: ").append(toIndentedString(modificado)).append("\n");
    sb.append("    prioridade: ").append(toIndentedString(prioridade)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

