/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Produto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProdutoResourceApi
 */
@Ignore
public class ProdutoResourceApiTest {

    private final ProdutoResourceApi api = new ProdutoResourceApi();

    
    /**
     * atualizaProduto
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void atualizaProdutoUsingPUTTest() throws ApiException {
        Produto produto = null;
        Produto response = api.atualizaProdutoUsingPUT(produto);

        // TODO: test validations
    }
    
    /**
     * deletaProduto
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deletaProdutoUsingDELETETest() throws ApiException {
        Produto produto = null;
        api.deletaProdutoUsingDELETE(produto);

        // TODO: test validations
    }
    
    /**
     * listaProdutoUnico
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listaProdutoUnicoUsingGETTest() throws ApiException {
        Long id = Long.valueOf(1);
        Produto response = api.listaProdutoUnicoUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * listaProdutos
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listaProdutosUsingGETTest() throws ApiException {
        List<Produto> response = api.listaProdutosUsingGET();

        // TODO: test validations
    }
    
    /**
     * salvaProduto
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void salvaProdutoUsingPOSTTest() throws ApiException {
        Produto produto = null;
        Produto response = api.salvaProdutoUsingPOST(produto);

        // TODO: test validations
    }
    
}
